public class PatientHelper
{
    public integer patientCode , age;
    public string patientName ,DrName, phoneNo, email , mailingAdress ;
    public date appointmentDate , ScheduleDate ;
    public decimal fees ;
    public boolean isInTreatment;
    }



/*
 PatientHelper pHelper = new PatientHelper ();


pHelper.patientCode = 4032 ;
pHelper.age = 45 ;
pHelper.patientName = 'sarika';
pHelper.DrName='shinde';
pHelper.phoneno='8446888690';
pHelper.email='sarika@gamil.com';
pHelper.mailingAdress='hyderabad';
pHelper.appointmentDate=system.today();
pHelper.ScheduleDate=system.today().addyears(3);
pHelper.fees=789.50;
pHelper.isInTreatment=true;


    system.debug('Patientcode is ....'+phelper.patientcode);
    system.debug('Patient age is ....'+pHelper.age);
    system.debug('Patient Name is ....'+pHelper.patientName);
    system.debug('Patient consultant dr... '+pHelper.DrName);
    system.debug('Patient phone number is '+pHelper.phoneno);
    system.debug(''+pHelper.email);
    system.debug(''+pHelper.mailingAdress);
    system.debug(''+pHelper.appointmentDate.format());
    system.debug(''+pHelper.ScheduleDate.format());
    system.debug(''+pHelper.fees);
    system.debug(''+pHelper.isInTreatment);

 
 */